### ISSUE TITLE
Allow avoiding double registering gauges (by making gauges accessible)

### ISSUE THREAD

**Issue by TheBeruriahIncident** [palantir/metric-schema#226]
In the large internal codebase @carterkozak and I work on, we use gauges. There have historically been issues with double registering gauges (through convoluted initialization, classpath issues, etc). This error surface made Carter cautious about gauges, and we were discussing how to remedy. One approach would be to precondition the gauge not being registered before registering it, which would ensure there's no double registration product bug that leads to other issues.

More concretely, supposing this schema:
```
options:
  javaPackage: com.palantir.metrics
namespaces:
  com.palantir.example:
    shortName: Example
    metrics:
      metric-without-tags:
        type: gauge
      metric-with-tag:
        type: gauge
        tags:
          - tag
```
The codegen gets a little bit added:
```
public final class ExampleMetrics {
    public void metricWithoutTags(Gauge<?> gauge) {
        registry.registerWithReplacement(
                MetricName.builder()
                        .safeName("com.palantir.metrics.example.metric.without.tags")
                        .build(),
                gauge);
    }

    // This is new!
    public Optional<Gauge<?>> metricWithoutTags() {
        registry.gauge(
                MetricName.builder()
                        .safeName("com.palantir.metrics.example.metric.without.tags")
                        .build());
    }


    public MetricWithTagBuilderTagStage metricWithTag() {
        return new MetricWithTagBuilder();
    }

    public interface MetricWithTagBuilderTagStage {
        MetricWithTagBuildStage tag(String tag);
    }

    public interface MetricWithTagBuildStage {
        // This is new!
        Optional<Gauge<?>> build();

        void build(Gauge<?> gauge);
    }
}
```
You could then consume it like:
```
Preconditions(!exampleMetrics.metricWithoutTags().isPresent(), "Gauge was double registered; this is a product bug")
exampleMetrics.metricWithoutTags(metricGetter)
```

This also helps with other use cases, like testing. Currently if you want to test a gauge, you have to duplicate the name string from codegen, which is ugly and fragile. To be up front, I had previously proposed basically the above in order to help with that testing usage (https://github.com/palantir/metric-schema/issues/23), but my proposal was rejected that no changes should be made for non-prod, testing usages. This now has a prod usage, and @carterkozak is now on board.

In terms of other options:
1) Do nothing. Leave gauges as dangerous.
2) Be more opinionated. E.g.
```
exampleMetrics.metricWithoutTags(metricGetter, BehaviorOnDoubleRegistration.THROW)
// or
exampleMetrics.metricWithoutTags(metricGetter, BehaviorOnDoubleRegistration.LOG)
```
Doing something like that and forcing people to opt in if they wanted riskier dangerous behavior has some advantages, but (as @carterkozak pointed out) it's more opinionated and we perhaps don't understand all use cases well enough to be strongly opinionated.

I'm happy to contribute this (it's just a few lines), but Carter wanted to be sure @iamdanfox and @ferozco were on board first.

**Comment by iamdanfox** [comment]
The getter method in the last builder stage looks a little funky:
```java
    public interface MetricWithTagBuildStage {
        Optional<Gauge<?>> build(); // should this say `get()` ??
        void build(Gauge<?> gauge);
    }
```

I think adding a `get` prefix might help differentiate these from the start of builders:

```groovy
Preconditions(!exampleMetrics.getMetricWithoutTags().isPresent(), "Gauge was double registered; this is a product bug")
```

**Comment by TheBeruriahIncident** [comment]
Those changes seem very reasonable. That brings the codegen to:
```
public final class ExampleMetrics {
    public void metricWithoutTags(Gauge<?> gauge) {
        registry.registerWithReplacement(
                MetricName.builder()
                        .safeName("com.palantir.metrics.example.metric.without.tags")
                        .build(),
                gauge);
    }

    // This is new!
    public Optional<Gauge<?>> getMetricWithoutTags() {
        registry.gauge(
                MetricName.builder()
                        .safeName("com.palantir.metrics.example.metric.without.tags")
                        .build());
    }


    public MetricWithTagBuilderTagStage metricWithTag() {
        return new MetricWithTagBuilder();
    }

    public interface MetricWithTagBuilderTagStage {
        MetricWithTagBuildStage tag(String tag);
    }

    public interface MetricWithTagBuildStage {
        // This is new!
        Optional<Gauge<?>> get();

        void build(Gauge<?> gauge);
    }
}
```
If that looks good to you, happy to implement.

**Comment by iamdanfox** [comment]
Actually hang on, the intended usage in the tagged case is going to result in people having to pass in all the parameters twice?

```
Preconditions.checkState(!FooMetrics.max().channelName(channelName).hostIndex(Integer.toString(uriIndex)).get().isPresent());
FooMetrics.max().channelName(channelName).hostIndex(Integer.toString(uriIndex)).build(func);
```
Seems like this could get error-prone if people have many (i.e >3) tags, especially if they're all numeric.

What about if we included the assertion in the builder chain itself? i.e. 

```java
FooMetrics.max()
.channelName(channelName)
.hostIndex(Integer
.toString(uriIndex))
.assertNotRegisteredAlready() // <- something like this?
.build(func)
```

**Comment by TheBeruriahIncident** [comment]
Ah, that's even better! I was thinking of saving the final stage and calling `get()` and then `build()`:
```
FooBuildStage fooBuildStage = FooMetrics.max()
  .channelName(channelName)
  .hostIndex(Integer.toString(uriIndex));
Preconditions(!fooBuildStage.get().isPresent(), "Gauge was double registered; this is a product bug")
fooBuildStage().build(func);
```
but you proposal is much more fluent and intuitive.  The problem though is that that it's not parallel with the untagged case unless we add something like:
```
    public void assertMetricWithoutTagsNotRegisteredAlready() {
```
Solely using this approach does eliminate the ability to also solve the testing problem, but that's not the worst.

**Comment by iamdanfox** [comment]
Another option could be to just bake it into the codegen and say every time we setup a gauge we verify it wasn't in there already?? I think all foundry services _should_ comply with this, and if they don't then I'm sure it's fixable with a little refactoring...

**Comment by TheBeruriahIncident** [comment]
As a naive newbie, that was definitely my preferred approach, but @carterkozak was worried that we can't know that all services comply. I would much prefer just baking it in if that's viable.

**Comment by iamdanfox** [comment]
ok so what if you have a featureflag that has three modes rather than two:

1. don't check
2. check and produce a log line if it's already registered
3. check and fail hard if the gauge is already in

Default would be (3)

**Comment by TheBeruriahIncident** [comment]
I like that. E.g. with this config:
```
options:
  javaPackage: com.palantir.metrics
namespaces:
  com.palantir.example:
    shortName: Example
    metrics:
      default-metric:
        type: gauge
      metric-with-logs:
        type: gauge
        on-double-registration: LOG
      unsafe-metric:
        type: gauge
        on-double-registration: IGNORE
```
You'd get this codegen:
```
public final class ExampleMetrics {
    private static final Logger LOGGER = LoggerFactory.get(ExampleMetrics.class);

    public void defaultMetric(Gauge<?> gauge) {
        MetricName name = MetricName.builder()
                .safeName("com.palantir.metrics.example.default.metric")
                .build()

        Preconditions.checkState(!registry.gauge(name).isPresent(), "Gauge was registered twice", SafeArg.of("name", name));
        registry.registerWithReplacement(name, gauge);
    }

    public void metricWithLogs(Gauge<?> gauge) {
        MetricName name = MetricName.builder()
                .safeName("com.palantir.metrics.example.metric.with.logs")
                .build()

        if (registry.gauge(name).isPresent()) {
            LOGGER.warn("Gauge was registered twice and is being overwritten", SafeArg.of("name", name));
        }
        registry.registerWithReplacement(name, gauge);
    }

    public void unsafeMetric(Gauge<?> gauge) {
        MetricName name = MetricName.builder()
                .safeName("com.palantir.metrics.example.unsafe.metric")
                .build()

        registry.registerWithReplacement(name, gauge);
    }
}
```
That said, I was originally pushing for this flavor of solution, and @carterkozak was quite worried that it wouldn't be viable since we'd break existing products. How confident are we that defaulting this way is safe?

**Comment by TheBeruriahIncident** [comment]
Synced with @ferozco and @carterkozak : the preference is for consumers to write a delegating implementation of `TaggedMetricRegistry` that detects this kind of errors and throws.
