### ISSUE TITLE
Allow removing metrics

### ISSUE THREAD

**Issue by a10y** [palantir/metric-schema#242]
Adding new metrics is a cinch, but removing metrics requires both

* hard-coding metric name in your code
* Plumbing down MetricRegistry/TaggedMetricRegistry to call its `#remove` method directly

We could potentially generate `remove*` methods for different generated metrics similar to the builders that are currently generated, curious if there are other thoughts here.

**Comment by carterkozak** [comment]
What does it mean to remove a metric? Can you describe the outcome you're looking for?

**Comment by a10y** [comment]
I define removing a metric the way `TaggedMetricRegistry#remove` defines it.

This is most useful for gauges, where I'm tracking a particular flow, and after that flow has concluded I'd like to clean up the metric so it stops reporting the last seen value

**Comment by carterkozak** [comment]
How do you ensure the final value has been recorded prior to removal?

**Comment by a10y** [comment]
In my mind the metrics recording and the metric registry are two separate components. If you have control over the recording process, you could ensure that any values you care about get flushed, and then remove that metric.

In practice, I believe the registry generally gets sampled by a background thread at regular intervals, and so there's no guarantee to the client that any specific measurement was ever recorded anyway.

**Comment by carterkozak** [comment]
This has come up a bit around testing as well, in general we've tried to discourage use of gauges and avoid special casing/complexity around them. How common is this pattern?

**Comment by a10y** [comment]
I can look thru internal codebases and see how prevalent it is, given that most products generally shy away from ephemeral/high-cardinality metrics of any kind my gut says maybe not very. If we think it's an anti-pattern then perhaps it doesn't belong in here. I'll poke around and report back.

**Comment by carterkozak** [comment]
Thanks!

**Comment by a10y** [comment]
So at least in AIP, we use ephemeral metrics very widely,  as measurements attached to specific streams and stream processors. When the stream or the processor is removed, the metric lingers currently. For some of these, we can suppress empty series for dashboards, but counters/gauges will continue to show up permanently.

**Comment by a10y** [comment]
Any thoughts on the right thing to do here? cc @ferozco  as well for input

**Comment by ferozco** [comment]
Totally understand the use case within AIP, but I don't think that its a very common pattern and worth adding support to metric-schema.

Could you continue to use the metric schema generated classes, but wrap the underlying metric registry so that it keeps track of metrics registered to it so you can remove them when the processor closes?
