### ISSUE TITLE
Relax metric name validation

### ISSUE THREAD

**Issue by schlosna** [palantir/metric-schema#274]
The metric name validation added in https://github.com/palantir/metric-schema/pull/271 prevents some previously permitted metric names such as `load.1` (system load over previous one minute) produced by tritium, causing [metric-schema upgrade bump to fail](https://github.com/palantir/tritium/pull/741).

We should consider relaxing the naming constraint to not require an alpha character before numeric after a period, e.g. using regex `[a-z][a-zA-Z0-9\-]+\.)*[a-zA-Z0-9\-]+`

```
* What went wrong:
Execution failed for task ':tritium-metrics-jvm:generateMetrics'.
> MetricDefinition names must match pattern: {pattern=([a-z][a-zA-Z0-9\-]+\.)*[a-z][a-zA-Z0-9\-]+, invalidTagName=load.1}
```

**Comment by carterkozak** [comment]
I'll take a look at this today, thanks for filing an issue!
