### ISSUE TITLE
Better typing for gauges

### ISSUE THREAD

**Issue by henryptung** [palantir/metric-schema#463]
Gauges declared in the current schema are untyped, and offer no compile-time checking of the returned type in code. This matches the assumptions of Codahale/Dropwizard metrics, but can conflict with some metrics aggregation systems/backends which e.g. assume numeric metric values.

Would be nice to be able to enforce this in a stronger compile-time way.

**Comment by carterkozak** [comment]
Great idea! I'd be happy to merge a change which generates `Gauge<? extends Number>` or similar :-)

**Comment by henryptung** [comment]
Addressing in #1040

**Comment by carterkozak** [comment]
resolved by #1040
